using FlowPlaylists.Misc;
using FlowPlaylists.UI;
using IPA;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;
using Logger = FlowPlaylists.Misc.Logger;

namespace FlowPlaylists
{
    public class Plugin : IBeatSaberPlugin
    {
        public static Plugin instance;
        public event Action<Queue<IBeatmapLevel>> levelsLoaded;

        private Queue<IBeatmapLevel> loadedLevels;

        public const string Name = "FlowPlaylists";
        public const string Version = "0.0.2";

        public Plugin() => instance = this;

        public void OnApplicationStart()
        {
        }

        public void OnSceneLoaded(Scene scene, LoadSceneMode sceneMode)
        {
            if (scene.name == "MenuCore")
            {
                SharedCoroutineStarter.instance.StartCoroutine(SetupUI());
            }
        }

        public void OnSceneUnloaded(Scene scene)
        {
        }

        public void OnActiveSceneChanged(Scene prevScene, Scene nextScene)
        {
            if (Config.Enabled && nextScene.name == "GameCore")
            {
                var stitcher = new GameObject("SongStitcher").AddComponent<SongStitcher>();
                levelsLoaded += stitcher.LevelsLoaded;

                var panel = CountdownPanel.Create();
                levelsLoaded += panel.LevelsLoaded;

                //If the levels were loaded prior to the scene change,
                //we can go ahead and re-invoke this to make sure our new
                //components have the right information
                if (loadedLevels != null)
                {
                    levelsLoaded?.Invoke(loadedLevels);
                    loadedLevels = null;
                }
            }
        }

        //Waits for menu scenes to be loaded then creates UI elements
        //Courtesy of BeatSaverDownloader
        private IEnumerator SetupUI()
        {
            List<Scene> menuScenes = new List<Scene>() { SceneManager.GetSceneByName("MenuCore"), SceneManager.GetSceneByName("MenuViewControllers"), SceneManager.GetSceneByName("MainMenu") };
            yield return new WaitUntil(() => { return menuScenes.All(x => x.isLoaded); });

            var standardLevelDetailViewController = Resources.FindObjectsOfTypeAll<StandardLevelDetailViewController>().FirstOrDefault();
            standardLevelDetailViewController.didPressPlayButtonEvent += didPressPlay;

            var missionLevelDetailViewController = Resources.FindObjectsOfTypeAll<MissionLevelDetailViewController>().FirstOrDefault();
            missionLevelDetailViewController.didPressPlayButtonEvent += didPressMissionPlay;

            var subMenu = CustomUI.Settings.SettingsUI.CreateSubMenu(Name);
            var showTimer = subMenu.AddBool("Show Timer");
            var timeSlider = subMenu.AddSlider("Playlist Duration", "Duration of the playlist generated by the random button", 0, 60 * 1000 * 60, 1, true);
            var gameOption = CustomUI.GameplaySettings.GameplaySettingsUI.CreateToggleOption($"Enable {Name}", "When you press play, songs after the song you select will be stitched together into one");
            var menuButton = CustomUI.MenuButton.MenuButtonUI.AddButton("Generate FlowPlaylist", "Play a randomly generated playlist with the length you specified in settings!", () => Logger.Error("NOT IMPLEMENTED"));

            Config.LoadConfig();
            gameOption.GetValue = Config.Enabled;
            gameOption.OnToggle += (b) =>
            {
                Config.Enabled = b;
                Config.SaveConfig();
            };
        }

        private void didPressMissionPlay(MissionLevelDetailViewController standardLevelDetailViewController)
        {
            levelsLoaded?.Invoke(null);
        }

        private async void didPressPlay(StandardLevelDetailViewController standardLevelDetailViewController)
        {
            var currentView = Resources.FindObjectsOfTypeAll<LevelPackLevelsTableView>().First();
            var currentPack = currentView.GetField<IBeatmapLevelPack>("_pack");
            var currentCollection = currentPack.beatmapLevelCollection;

            var newCollection = currentCollection.beatmapLevels.SkipWhile(x => x.levelID != standardLevelDetailViewController.selectedDifficultyBeatmap.level.levelID);

            //If we're dealing with DLC, we have to load all the levels that the user has
            //now, because loading them mid-Update() would require Update to be async,
            //and *that* would cause multiple level loads to be started before the first level load finishes
            if (!(newCollection.First() is IBeatmapLevel))
            {
                loadedLevels = new Queue<IBeatmapLevel>();

                foreach (var level in newCollection.ToList())
                {
                    if (await SongHelpers.HasDLCLevel(level.levelID))
                    {
                        var result = await SongHelpers.GetDLCLevel(level);
                        if (result != null && !(result?.isError == true))
                        {
                            loadedLevels.Enqueue(result?.beatmapLevel);
                        }
                    }
                }
            }
            else loadedLevels = new Queue<IBeatmapLevel>(newCollection.Select(x => x as IBeatmapLevel));

            levelsLoaded?.Invoke(loadedLevels);
        }

        public void OnApplicationQuit()
        {
        }

        public void OnLevelWasLoaded(int level)
        {

        }

        public void OnLevelWasInitialized(int level)
        {
        }

        public void OnUpdate()
        {
        }

        public void OnFixedUpdate()
        {
        }
    }
}
